# -*- coding: utf-8 -*-
"""LibraryManagementSystem

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lkm_fITwaFxSQ-KImNZRgU3oi1MHnd2O
"""



class Library:
  def __init__ (self,filename):
    self.file=open(filename,"a+")
  def __del__ (self):
    self.file.close()
  def ListBooks(self):
    self.file.seek(0)
    lines=self.file.read().splitlines()
    #print(lines)
    for each in lines:
      each_book=each.split(",")
      print(each_book[0],each_book[1])

  def AddBooks(self):
    book_title=input("Book Title: ")
    book_author=input("Author: ")
    first_release_year=input("First Release Year: ")
    number_of_pages=input("Number of Pages: ")
    new_book=f"{book_title}, {book_author}, {first_release_year}, {number_of_pages}\n"
    self.file.write(new_book)

  def RemoveBooks(self):
    self.file.seek(0)
    book_title=input("Book Title: ")
    lines=self.file.readlines()
    new_list=[]
    for line in lines:
      each_book=line.split(",")
      if each_book[0]!=book_title:
        new_list.append(line)
    self.file.seek(0)
    self.file.truncate()

    self.file.writelines(new_list)



lib=Library("books.txt")
print("***MENU***")
print("1) List Books")
print("2) Add Books")
print("3) Remove Books")
print("4) Quit")
choice=int(input("What is your choice: "))
if choice==1:
  lib.ListBooks()
elif choice==2:
  lib.AddBooks()
elif choice==3:
  lib.RemoveBooks()
else:
  print("Exit")





